[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
splitterprogram = "EbSG8YorD2N1QHoiayDba3cuDQsyUJ7ysocjHVaLb9b5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/berkay/sparkwallets/devQysppie8pvwpbAi1BR49RagKVPBkksqNTHCiFNJg.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
